### PR TITLE
Create setup scripts for Linux and OSX

### LINKED ISSUE #2: Create seamless setup script
This script should be able to install ruby, rails, and all the correct dependencies of the application. 

The goal is to allow users to pull the repo, run this script, and be able to run the app right after.

### PR DESCRIPTION
**Pull request by EricPickup**
### What are you trying to do?

Closes #2 

I took the popular setup scripts from https://github.com/railsgirls/installation-scripts and modified them a tiny bit to match our ruby versions and added a few more commands tailored to this project.

### Is there anything reviewers should know?

Tested with Linux, untested for OSX but perhaps @DSchana can try it out? 👀

### CODE REVIEW

**Comment by EricPickup** [comment]
Updated the PR to reflect the changes from #10. The script will now install those new versions of Ruby and Rails. Ready for review/testing @DSchana

**Comment by EricPickup** [comment]
@DSchana added a script for arch https://github.com/UWindsor/vcar-web/blob/94da8cc38d6a6c30c4256918565374bd0d6863df/scripts/rails-install-archlinux.sh

**Review by DSchana — COMMENTED** [review]
Had error retrieving GPG keys. It recommended I run this:
```
curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
curl -sSL https://rvm.io/pkuczynski.asc | gpg2 --import -
```
Which seemed to resolve the issue, idk if that's the way it should be done though.

Also, Error while executing gem. Invalid option: --no-rdoc.

**Comment by EricPickup** [comment]
Thanks @DSchana, I've updated the script. Lmk how it goes

**Pull request closed without merging**
